language: node_js
node_js:
  - "8"
  - "10"
os: linux
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install: yarn
before_script: sh -c "git log | head -12"
script: yarn run coverage
after_success:
  - coveralls < ./coverage/lcov.info
  - CODECLIMATE_REPO_TOKEN=1a43bb0ff5569a39f4e9a90353b17bc607a18fa3de1d0a346ae0bb76e7f4fa98 codeclimate-test-reporter < ./coverage/lcov.info
