language: node_js
node_js:
  - "4"
  - "6"
  - "7"
os: linux
sudo: false
install: npm install
before_script: sh -c "git log | head -12"
script: npm run coverage
after_success:
  - coveralls < ./coverage/lcov.info
  - CODECLIMATE_REPO_TOKEN=1a43bb0ff5569a39f4e9a90353b17bc607a18fa3de1d0a346ae0bb76e7f4fa98 codeclimate-test-reporter < ./coverage/lcov.info
