name: Build
on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn run lint

  Test:
    needs: Lint
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: ["14.19.1", "16.14.2", "18.0.0"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
        env:
          SNOOPLOGG: "*"

  MacOSTest:
    needs: Lint
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: ["16.14.2", "18.0.0"]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
        env:
          SNOOPLOGG: "*"

  MacOS14Test:
    needs: Lint
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: ["14.21.3"]
        os: [macos-14-arm64]
        arch: arm64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
        env:
          SNOOPLOGG: "*"
